language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install
  - mkdir -p build/cov
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

script:
  - ./vendor/bin/phpunit --coverage-text tests

after_script:
  - php vendor/bin/coveralls -v
