language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install
  - mkdir -p build/cov
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

script:
  - ./vendor/bin/phpunit --coverage-text tests

after_script:
  - php vendor/bin/coveralls -v
  - CODECLIMATE_REPO_TOKEN=a15d02e7151a8bdd326349a94309e3f7ce4181e21e3f01d7304232ef2b8525ad ./vendor/bin/test-reporter --coverage-report=build/cov/clover.xml
